// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCP7rRH3TqEz0QWBn6MzltqVy55-VBScE',
    appId: '1:336296168636:web:629a506dea3da778ba14b9',
    messagingSenderId: '336296168636',
    projectId: 'inventory-management-30c15',
    authDomain: 'inventory-management-30c15.firebaseapp.com',
    storageBucket: 'inventory-management-30c15.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBhWqPV3Vlny5iAMAUAY9r2-z2LtfcGkY',
    appId: '1:336296168636:android:9dbfc96a0342d17fba14b9',
    messagingSenderId: '336296168636',
    projectId: 'inventory-management-30c15',
    storageBucket: 'inventory-management-30c15.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDV_9PDO-Dk8qeChkoZifOWEabiaJy7DHU',
    appId: '1:336296168636:ios:2c8645945865ffa5ba14b9',
    messagingSenderId: '336296168636',
    projectId: 'inventory-management-30c15',
    storageBucket: 'inventory-management-30c15.firebasestorage.app',
    iosBundleId: 'com.example.inventory',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDV_9PDO-Dk8qeChkoZifOWEabiaJy7DHU',
    appId: '1:336296168636:ios:2c8645945865ffa5ba14b9',
    messagingSenderId: '336296168636',
    projectId: 'inventory-management-30c15',
    storageBucket: 'inventory-management-30c15.firebasestorage.app',
    iosBundleId: 'com.example.inventory',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBCP7rRH3TqEz0QWBn6MzltqVy55-VBScE',
    appId: '1:336296168636:web:f229bb5f1431c6a7ba14b9',
    messagingSenderId: '336296168636',
    projectId: 'inventory-management-30c15',
    authDomain: 'inventory-management-30c15.firebaseapp.com',
    storageBucket: 'inventory-management-30c15.firebasestorage.app',
  );
}
